const datosVentasFin = [
  {
    id: "1",
    expediente: "EXP-00456",
    fechaSolicitud: "2025-06-02",
    tipoSolicitud: "Registro",
    tipoPersona: "Jurídica",
    titular: "TechWorld Inc.",
    marca: "NeoVision",
    encargado: "Dra. Rivera",
    proximaCita: "2025-07-05",
    estado: "Activo",
  },
  {
    id: "2",
    expediente: "EXP-00457",
    fechaSolicitud: "2025-06-05",
    tipoSolicitud: "Cesión",
    tipoPersona: "Natural",
    titular: "Luis Torres",
    marca: "EcoPlus",
    encargado: "Dr. Herrera",
    proximaCita: "",
    estado: "En revisión",
  },
  {
    id: "3",
    expediente: "EXP-00458",
    fechaSolicitud: "2025-06-08",
    tipoSolicitud: "Renovación",
    tipoPersona: "Jurídica",
    titular: "GreenTech SAS",
    marca: "GreenSoft",
    encargado: "Dra. Martínez",
    proximaCita: "2025-06-30",
    estado: "Pendiente firma",
  },
  {
    id: "4",
    expediente: "EXP-00459",
    fechaSolicitud: "2025-06-12",
    tipoSolicitud: "Registro",
    tipoPersona: "Natural",
    titular: "Andrea Ruiz",
    marca: "ArticZone",
    encargado: "Dr. Castaño",
    proximaCita: "2025-07-15",
    estado: "Pendiente",
  },
  {
    id: "5",
    expediente: "EXP-00460",
    fechaSolicitud: "2025-06-15",
    tipoSolicitud: "Ampliación",
    tipoPersona: "Jurídica",
    titular: "Innova Group",
    marca: "InnovaTech",
    encargado: "Dra. Rojas",
    proximaCita: "",
    estado: "Cancelado",
  },
];

export default datosVentasFin;
