const dataClientes = [
  {
    tipoDocumento: "CC",
    documento: "1001234567",
    nombre: "Carlos",
    apellido: "Pérez",
    email: "carlos.perez@example.com",
    telefono: "3001234567",
    nitEmpresa: "900123456",
    nombreEmpresa: "Soluciones S.A.S.",
    marca: "SolTech",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "CE",
    documento: "1009876543",
    nombre: "Luisa",
    apellido: "Gómez",
    email: "luisa.gomez@example.com",
    telefono: "3019876543",
    nitEmpresa: "900987654",
    nombreEmpresa: "Innovar Ltda.",
    marca: "Innova",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "CC",
    documento: "1012345678",
    nombre: "Ana",
    apellido: "Martínez",
    email: "ana.martinez@example.com",
    telefono: "3023456789",
    nitEmpresa: "901234567",
    nombreEmpresa: "Creativos S.A.",
    marca: "Creativa",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "TI",
    documento: "1023456789",
    nombre: "Julián",
    apellido: "Ramírez",
    email: "julian.ramirez@example.com",
    telefono: "3101234567",
    nitEmpresa: "902345678",
    nombreEmpresa: "Empaques Express",
    marca: "EmpaqX",
    tipoPersona: "Natural"
  },
  {
    tipoDocumento: "CC",
    documento: "1034567890",
    nombre: "Diana",
    apellido: "Rodríguez",
    email: "diana.rodriguez@example.com",
    telefono: "3112345678",
    nitEmpresa: "903456789",
    nombreEmpresa: "Servicios Integrales",
    marca: "ServiInt",
    tipoPersona: "Natural"
  },
  {
    tipoDocumento: "NIT",
    documento: "1045678901",
    nombre: "Esteban",
    apellido: "Moreno",
    email: "esteban.moreno@example.com",
    telefono: "3123456789",
    nitEmpresa: "904567890",
    nombreEmpresa: "Logística Total",
    marca: "LogiT",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "CC",
    documento: "1056789012",
    nombre: "Marcela",
    apellido: "López",
    email: "marcela.lopez@example.com",
    telefono: "3134567890",
    nitEmpresa: "905678901",
    nombreEmpresa: "Eventos y Más",
    marca: "EventPlus",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "NIT",
    documento: "1067890123",
    nombre: "Andrés",
    apellido: "García",
    email: "andres.garcia@example.com",
    telefono: "3145678901",
    nitEmpresa: "906789012",
    nombreEmpresa: "Marketing Creativo",
    marca: "MKTG",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "PEP",
    documento: "1078901234",
    nombre: "Camila",
    apellido: "Ríos",
    email: "camila.rios@example.com",
    telefono: "3156789012",
    nitEmpresa: "907890123",
    nombreEmpresa: "ConstruRed",
    marca: "Construx",
    tipoPersona: "Natural"
  },
  {
    tipoDocumento: "CC",
    documento: "1089012345",
    nombre: "Jorge",
    apellido: "Salazar",
    email: "jorge.salazar@example.com",
    telefono: "3167890123",
    nitEmpresa: "908901234",
    nombreEmpresa: "Redes Globales",
    marca: "RedGlobal",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "CC",
    documento: "1090123456",
    nombre: "Valentina",
    apellido: "Castro",
    email: "valentina.castro@example.com",
    telefono: "3178901234",
    nitEmpresa: "909012345",
    nombreEmpresa: "Diseños V",
    marca: "Diseña",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "TI",
    documento: "1101234567",
    nombre: "Sebastián",
    apellido: "Mejía",
    email: "sebastian.mejia@example.com",
    telefono: "3189012345",
    nitEmpresa: "910123456",
    nombreEmpresa: "Muebles Modernos",
    marca: "Muebliar",
    tipoPersona: "Natural"
  },
  {
    tipoDocumento: "CE",
    documento: "1112345678",
    nombre: "Paola",
    apellido: "Ortiz",
    email: "paola.ortiz@example.com",
    telefono: "3190123456",
    nitEmpresa: "911234567",
    nombreEmpresa: "Estilo Urbano",
    marca: "Urbania",
    tipoPersona: "Natural"
  },
  {
    tipoDocumento: "CC",
    documento: "1123456789",
    nombre: "Juan",
    apellido: "Navarro",
    email: "juan.navarro@example.com",
    telefono: "3201234567",
    nitEmpresa: "912345678",
    nombreEmpresa: "EcoServicios",
    marca: "EcoPlus",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "PAS",
    documento: "1134567890",
    nombre: "Karen",
    apellido: "Hernández",
    email: "karen.hernandez@example.com",
    telefono: "3212345678",
    nitEmpresa: "913456789",
    nombreEmpresa: "Artes Gráficas",
    marca: "Grafix",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "CC",
    documento: "1145678901",
    nombre: "Mateo",
    apellido: "Lara",
    email: "mateo.lara@example.com",
    telefono: "3223456789",
    nitEmpresa: "914567890",
    nombreEmpresa: "AgroCampo",
    marca: "AgroVida",
    tipoPersona: "Natural"
  },
  {
    tipoDocumento: "NIT",
    documento: "1156789012",
    nombre: "Tatiana",
    apellido: "Mendoza",
    email: "tatiana.mendoza@example.com",
    telefono: "3234567890",
    nitEmpresa: "915678901",
    nombreEmpresa: "Transportes T&M",
    marca: "T&M",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "CC",
    documento: "1167890123",
    nombre: "Felipe",
    apellido: "Reyes",
    email: "felipe.reyes@example.com",
    telefono: "3245678901",
    nitEmpresa: "916789012",
    nombreEmpresa: "Software Factory",
    marca: "SoftFac",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "PEP",
    documento: "1178901234",
    nombre: "Lorena",
    apellido: "Cano",
    email: "lorena.cano@example.com",
    telefono: "3256789012",
    nitEmpresa: "917890123",
    nombreEmpresa: "Belleza Natural",
    marca: "Bellu",
    tipoPersona: "Natural"
  },
  {
    tipoDocumento: "CC",
    documento: "1189012345",
    nombre: "Ricardo",
    apellido: "Silva",
    email: "ricardo.silva@example.com",
    telefono: "3267890123",
    nitEmpresa: "918901234",
    nombreEmpresa: "Consulting Pro",
    marca: "ConsultPro",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "CC",
    documento: "1190123456",
    nombre: "Juliana",
    apellido: "Arango",
    email: "juliana.arango@example.com",
    telefono: "3278901234",
    nitEmpresa: "919012345",
    nombreEmpresa: "Eventos VIP",
    marca: "VIPevent",
    tipoPersona: "Natural"
  },
  {
    tipoDocumento: "CC",
    documento: "1201234567",
    nombre: "Tomás",
    apellido: "Osorio",
    email: "tomas.osorio@example.com",
    telefono: "3289012345",
    nitEmpresa: "920123456",
    nombreEmpresa: "Impresos Rápidos",
    marca: "Impresol",
    tipoPersona: "Natural"
  },
  {
    tipoDocumento: "TI",
    documento: "1212345678",
    nombre: "Isabela",
    apellido: "Guerra",
    email: "isabela.guerra@example.com",
    telefono: "3290123456",
    nitEmpresa: "921234567",
    nombreEmpresa: "Panadería Central",
    marca: "PanCentral",
    tipoPersona: "Natural"
  },
  {
    tipoDocumento: "CC",
    documento: "1223456789",
    nombre: "Mario",
    apellido: "Jiménez",
    email: "mario.jimenez@example.com",
    telefono: "3301234567",
    nitEmpresa: "922345678",
    nombreEmpresa: "Distribuciones Jiménez",
    marca: "DistriJ",
    tipoPersona: "Jurídica"
  },
  {
    tipoDocumento: "CC",
    documento: "1234567890",
    nombre: "Natalia",
    apellido: "Vergara",
    email: "natalia.vergara@example.com",
    telefono: "3312345678",
    nitEmpresa: "923456789",
    nombreEmpresa: "Moda Urbana",
    marca: "ModaUrb",
    tipoPersona: "Jurídica"
  }
];

export default dataClientes;
