// Archivo utilitario de países con bandera y código ISO
export const PAISES = [
  { nombre: "Afganistán", codigo: "AF", bandera: "https://flagcdn.com/af.svg" },
  { nombre: "Alemania", codigo: "DE", bandera: "https://flagcdn.com/de.svg" },
  { nombre: "Argentina", codigo: "AR", bandera: "https://flagcdn.com/ar.svg" },
  { nombre: "Australia", codigo: "AU", bandera: "https://flagcdn.com/au.svg" },
  { nombre: "Bolivia", codigo: "BO", bandera: "https://flagcdn.com/bo.svg" },
  { nombre: "Brasil", codigo: "BR", bandera: "https://flagcdn.com/br.svg" },
  { nombre: "Canadá", codigo: "CA", bandera: "https://flagcdn.com/ca.svg" },
  { nombre: "Chile", codigo: "CL", bandera: "https://flagcdn.com/cl.svg" },
  { nombre: "China", codigo: "CN", bandera: "https://flagcdn.com/cn.svg" },
  { nombre: "Colombia", codigo: "CO", bandera: "https://flagcdn.com/co.svg" },
  { nombre: "Costa Rica", codigo: "CR", bandera: "https://flagcdn.com/cr.svg" },
  { nombre: "Cuba", codigo: "CU", bandera: "https://flagcdn.com/cu.svg" },
  { nombre: "Ecuador", codigo: "EC", bandera: "https://flagcdn.com/ec.svg" },
  { nombre: "Egipto", codigo: "EG", bandera: "https://flagcdn.com/eg.svg" },
  {
    nombre: "El Salvador",
    codigo: "SV",
    bandera: "https://flagcdn.com/sv.svg",
  },
  { nombre: "España", codigo: "ES", bandera: "https://flagcdn.com/es.svg" },
  {
    nombre: "Estados Unidos",
    codigo: "US",
    bandera: "https://flagcdn.com/us.svg",
  },
  { nombre: "Francia", codigo: "FR", bandera: "https://flagcdn.com/fr.svg" },
  { nombre: "Guatemala", codigo: "GT", bandera: "https://flagcdn.com/gt.svg" },
  { nombre: "Honduras", codigo: "HN", bandera: "https://flagcdn.com/hn.svg" },
  { nombre: "India", codigo: "IN", bandera: "https://flagcdn.com/in.svg" },
  { nombre: "Italia", codigo: "IT", bandera: "https://flagcdn.com/it.svg" },
  { nombre: "Japón", codigo: "JP", bandera: "https://flagcdn.com/jp.svg" },
  { nombre: "México", codigo: "MX", bandera: "https://flagcdn.com/mx.svg" },
  { nombre: "Nicaragua", codigo: "NI", bandera: "https://flagcdn.com/ni.svg" },
  { nombre: "Panamá", codigo: "PA", bandera: "https://flagcdn.com/pa.svg" },
  { nombre: "Paraguay", codigo: "PY", bandera: "https://flagcdn.com/py.svg" },
  { nombre: "Perú", codigo: "PE", bandera: "https://flagcdn.com/pe.svg" },
  { nombre: "Portugal", codigo: "PT", bandera: "https://flagcdn.com/pt.svg" },
  {
    nombre: "Reino Unido",
    codigo: "GB",
    bandera: "https://flagcdn.com/gb.svg",
  },
  {
    nombre: "República Dominicana",
    codigo: "DO",
    bandera: "https://flagcdn.com/do.svg",
  },
  { nombre: "Rusia", codigo: "RU", bandera: "https://flagcdn.com/ru.svg" },
  { nombre: "Uruguay", codigo: "UY", bandera: "https://flagcdn.com/uy.svg" },
  { nombre: "Venezuela", codigo: "VE", bandera: "https://flagcdn.com/ve.svg" },
  // ...agrega más países si lo deseas
];
